config/routes.rb
Rails.application.routes.draw do
  
  root :to =>"memos#index"
  resources :memos, only: [:index, :create, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    @memo = Memo.new
    @memos = Memo.all
  end

  def create
    @memo = Memo.new(memos_params)
    @memo.save
    redirect_to  request.referer
  end

  def update
    @memo = Memo.find(params[:id])
    @memo.update(memos_params)
    redirect_to  request.referer
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to  request.referer
  end

  private

  def memos_params
    params.require(:memo).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="heading">
        <h1 class="font">メモ帳</h1>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/memos/edit.html.erb
<h1>Memos#edit</h1>
<p>Find me in app/views/memos/edit.html.erb</p>

app/views/memos/index.html.erb
<%= form_with model: @memo, method: :post do |f| %>
  <%= f.label:タイトル %>
  <%= f.text_field :title %>
  <%= f.label:メモ %>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

<% @memos.each do |memo| %>
  <%= form_with model: memo, url: memo_path(memo.id), method: :patch do |f| %>
    <%= f.label:タイトル %>
    <%= f.text_field :title %>
    <%= f.label:メモ %>
    <%= f.text_area :body %>
    <%= f.submit '更新' %>
  <% end %>
  <%= button_to "削除", memo_path(memo.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/memos/show.html.erb
<h1>Memos#show</h1>
<p>Find me in app/views/memos/show.html.erb</p>